name: Build and Release Binaries

on:
  push:
    tags:
      - "v*" # Trigger workflow on version tags (e.g., v1.0.0)

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        target:
          [x86_64-unknown-linux-gnu, x86_64-apple-darwin, x86_64-pc-windows-gnu]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Install Rust Target for Cross-Compilation
        run: rustup target add ${{ matrix.target }}

      - name: Install Cross-Compilation
        run: cargo install cross

      - name: Build Binary
        run: cross build --release --target ${{ matrix.target }}

      - name: Package Binary
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            mkdir -p dist
            cp target/${{ matrix.target }}/release/co-processor-cli.exe dist/
            powershell Compress-Archive -Path dist/* -DestinationPath co-processor-cli-${{ matrix.target }}.zip
          else
            if [[ -f target/x86_64-apple-darwin/release/co-processor-cli ]]; then
              TARGET_DIR="x86_64-apple-darwin"
            elif [[ -f target/x86_64-unknown-linux-gnu/release/co-processor-cli ]]; then
              TARGET_DIR="x86_64-unknown-linux-gnu"
            else
              echo "Error: Target binary not found in expected paths."
              exit 1
            fi

            mkdir -p dist
            cp target/$TARGET_DIR/release/co-processor-cli dist/
            tar -czvf co-processor-cli-$TARGET_DIR.tar.gz -C dist .
          fi

      - name: Upload Packaged Binary
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-packaged
          path: |
            co-processor-cli-${{ matrix.target }}.zip
            co-processor-cli-${{ matrix.target }}.tar.gz

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            co-processor-cli-${{ matrix.target }}.zip
            co-processor-cli-${{ matrix.target }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
