name: Build and Release Binaries

on:
  push:
    tags:
      - "v*" # Trigger workflow on version tags (e.g., v1.0.0)

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            archive: tar.gz tar.xz
          - target: x86_64-apple-darwin
            os: macos-latest
            archive: tar.gz
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            archive: tar.gz
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          profile: minimal

      - name: Install Rust Target for Cross-Compilation
        run: rustup target add ${{ matrix.target }}

      - name: Build and test
        run: cargo build --target ${{ matrix.target }} --release --verbose

      - name: Package Binary
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            mkdir -p dist
            cp target/${{ matrix.target }}/release/co-processor-cli.exe dist/
            powershell Compress-Archive -Path dist/* -DestinationPath co-processor-cli-${{ matrix.target }}.zip
          else
            mkdir -p dist
            cp target/${{ matrix.target }}/release/co-processor-cli dist/
            tar -czvf co-processor-cli-${{ matrix.target }}.tar.gz -C dist .
          fi
