name: Build and Release Binaries

on:
  push:
    tags:
      - "v*" # Trigger workflow on version tags (e.g., v1.0.0)

jobs:
  build_mac:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          profile: minimal

      - name: Install rust target for cross-compilation
        uses: actions-rs/cargo@v1
        with:
          command: target add ${{ matrix.target }}

      - name: Build and test
        run: cargo build --target ${{ matrix.target }} --release --verbose
